//+------------------------------------------------------------------+
//|                                          GoldMultiStrategyEA.mq5 |
//|                                    Generated by MetaEditor      |
//|                                                                  |
//| Multi-Strategy Gold Trading Bot - 4 strategies integrated       |
//+------------------------------------------------------------------+
#property copyright "Advanced Gold EA"
#property link      ""
#property version   "3.13"
#property description "Multi-Strategy Expert Advisor for Gold (XAUUSD)"
#property description "EMA / RSI / Bollinger / Momentum + Signal Quality Scoring"
#property description "Trailing-stop exits (no fixed TP), HTF trend filter, ATR trailing,"
#property description "spread & news guards, working portfolio-risk and daily limits"

//+------------------------------------------------------------------+
//| INPUT PARAMETERS (Customizable by user in MT5)                 |
//+------------------------------------------------------------------+

//--- System Settings
input string   sys1 = "═════════ SYSTEM SETTINGS ═════════";        // --- SYSTEM SETTINGS ---
input ulong    MagicNumber = 202411;                                // EA Magic Number
input bool     TradeLong = true;                                    // Allow Long (BUY) Trades
input bool     TradeShort = true;                                   // Allow Short (SELL) Trades
input int      MaxConcurrentTrades = 2;                             // Max Simultaneous Positions
input bool     UseTimeFilter = false;                               // Restrict Trading Hours
input int      StartHour = 8;                                       // Trading Start Hour (Broker Time)
input int      EndHour = 20;                                        // Trading End Hour (Broker Time)

//--- Risk Management
input string   risk1 = "══════════ RISK MANAGEMENT ══════════";     // --- RISK MANAGEMENT ---
input double   RiskPerTrade = 1.0;                                  // Risk % per Trade (0.5-2.0)
input double   MaxDailyDrawdown = 5.0;                              // Max Daily Drawdown %
input double   MaxTotalRisk = 6.0;                                  // Max Concurrent Portfolio Risk %
input double   DailyProfitTargetPct = 5.0;                          // Daily Profit Target % (0 = disabled)
input int      MaxDailyTrades = 10;                                 // Max Trades Per Day
input int      MaxSpreadPoints = 50;                                // Max allowed spread (points) to enter
input bool     UseBreakeven = true;                                 // Auto-Breakeven at X pips
input int      BreakevenTrigger = 15;                               // Breakeven trigger points (10-20)
input bool     UseTrailingStop = true;                              // Enable Trailing Stop
input int      TrailingStart = 40;                                  // Trailing start points (20-40)
input int      TrailingStep = 30;                                   // Trailing step points (fixed-mode)
input bool     UsePartialClose = false;                             // Enable Partial Profit Taking (OFF = keep full size)
input double   PartialClosePercent = 50.0;                          // % to close at 1st TP
input double   RiskRewardRatio = 2.5;                               // Risk:Reward Ratio (unused: TP is trailing-only)
input double   SL_ATR_Multiplier = 1.2;                             // Initial Stop = this x ATR

//--- Strength Filters (NEW)
input string   filt1 = "══════════ STRENGTH FILTERS ══════════";    // --- STRENGTH FILTERS ---
input bool     EnableTrendFilter = true;                            // Only trade WITH higher-timeframe trend
input ENUM_TIMEFRAMES TrendTimeframe = PERIOD_H1;                   // Trend Filter Timeframe
input int      TrendMAPeriod = 200;                                 // Trend Filter EMA Period
input bool     OneTradePerDirection = true;                         // Block stacking same-direction trades
input bool     UseATRTrailing = true;                               // Trail by ATR (adapts to volatility)
input double   TrailATRMultiplier = 1.5;                            // Trailing distance = this x ATR
input bool     EnableNewsFilter = false;                            // Pause around high-impact USD news
input int      NewsMinutesBefore = 30;                              // Pause minutes BEFORE news
input int      NewsMinutesAfter = 30;                               // Pause minutes AFTER news

//--- Strategy Selection & Quality
input string   strat1 = "══════════ STRATEGY SETUP ══════════";     // --- STRATEGY SETUP ---
input bool     EnableStrategy1 = true;                              // 1. EMA 9/21 Crossover
input bool     EnableStrategy2 = true;                              // 2. RSI Momentum Strategy
input bool     EnableStrategy3 = true;                              // 3. Bollinger Bands Strategy
input bool     EnableStrategy4 = true;                              // 4. Intraday Momentum Strategy
input double   MinSignalQuality = 65.0;                             // Min Signal Quality (0-100) - 60-70 recommended
input int      RSI_Period = 14;                                     // RSI Period
input double   RSI_Overbought = 70;                                 // RSI Overbought Level
input double   RSI_Oversold = 30;                                   // RSI Oversold Level
input int      BB_Period = 20;                                      // Bollinger Bands Period
input double   BB_Deviation = 2.0;                                  // Bollinger Bands Deviation
input double   MomentumVolatilityMultiplier = 1.5;                  // Momentum Min Volatility Multiplier

//--- Indicator Settings
input string   ind1 = "═══════════ INDICATOR SETTINGS ═════════";   // --- INDICATOR SETTINGS ---
input int      FastMAPeriod = 9;                                    // Fast EMA Period
input int      SlowMAPeriod = 21;                                   // Slow EMA Period
input int      ADXPeriod = 14;                                      // ADX Period for Trend Filter
input int      ADXThreshold = 20;                                   // ADX Minimum (20-25)
input int      ATRPeriod = 14;                                      // ATR Period for Dynamic SL/TP

//--- Debug mode (prints signal details)
input bool     DebugMode = true;                                    // Enable debug prints in Experts tab
input bool     DiagnosticMode = false;                              // TEST ONLY: loosen all filters to confirm trading

//+------------------------------------------------------------------+
//| GLOBAL VARIABLES                                                |
//+------------------------------------------------------------------+
double g_atrValue = 0;
double g_dailyDrawdown = 0;
int g_tradesToday = 0;
datetime g_lastReset = 0;
double g_initialBalance = 0;   // balance at start of the trading day
double g_highestEquity = 0;
bool g_tradingHalted = false;  // set true when a daily limit/target is hit

//--- Effective filter settings (loosened when DiagnosticMode is ON)
bool   eff_EnableTrendFilter;
bool   eff_EnableNewsFilter;
double eff_MinSignalQuality;
int    eff_ADXThreshold;
int    eff_MaxSpreadPoints;

//--- Strategy Signal Scoring
struct SignalData {
   double quality;     // Signal quality score (0-100)
   int direction;      // 1 = BUY, -1 = SELL, 0 = NEUTRAL
};

//--- Indicator Handles
int handle_EMA_Fast;
int handle_EMA_Slow;
int handle_RSI;
int handle_BB;
int handle_ADX;
int handle_ATR;
int handle_TrendMA;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   //--- Validate inputs
   if(RiskPerTrade < 0.1 || RiskPerTrade > 5.0) {
      Print("WARNING: RiskPerTrade should be between 0.1 and 5.0");
      return(INIT_PARAMETERS_INCORRECT);
   }

   //--- Initialize indicator handles
   handle_EMA_Fast = iMA(_Symbol, PERIOD_M5, FastMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handle_EMA_Slow = iMA(_Symbol, PERIOD_M5, SlowMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handle_RSI = iRSI(_Symbol, PERIOD_M5, RSI_Period, PRICE_CLOSE);
   handle_BB = iBands(_Symbol, PERIOD_M5, BB_Period, 0, BB_Deviation, PRICE_CLOSE);  // FIXED: correct arg order (shift=0, deviation=BB_Deviation)
   handle_ADX = iADX(_Symbol, PERIOD_M5, ADXPeriod);
   handle_ATR = iATR(_Symbol, PERIOD_M5, ATRPeriod);
   handle_TrendMA = iMA(_Symbol, TrendTimeframe, TrendMAPeriod, 0, MODE_EMA, PRICE_CLOSE);

   if(handle_EMA_Fast == INVALID_HANDLE || handle_EMA_Slow == INVALID_HANDLE ||
      handle_RSI == INVALID_HANDLE || handle_BB == INVALID_HANDLE ||
      handle_ADX == INVALID_HANDLE || handle_ATR == INVALID_HANDLE ||
      handle_TrendMA == INVALID_HANDLE) {
      Print("Error creating indicator handles. Check input parameters.");
      return(INIT_FAILED);
   }

   //--- Initialize global tracking
   g_initialBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   g_highestEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   g_tradesToday = 0;
   g_tradingHalted = false;
   g_lastReset = iTime(_Symbol, PERIOD_D1, 0);
   g_atrValue = CalculateATRValue();

   //--- Set effective filter values (DiagnosticMode loosens everything for testing)
   if(DiagnosticMode) {
      eff_EnableTrendFilter = false;
      eff_EnableNewsFilter  = false;
      eff_MinSignalQuality  = 0;
      eff_ADXThreshold      = 1;
      eff_MaxSpreadPoints   = 1000000;
      Print(">>> DIAGNOSTIC MODE ON: filters loosened to verify the EA can trade. Turn OFF for real use. <<<");
   } else {
      eff_EnableTrendFilter = EnableTrendFilter;
      eff_EnableNewsFilter  = EnableNewsFilter;
      eff_MinSignalQuality  = MinSignalQuality;
      eff_ADXThreshold      = ADXThreshold;
      eff_MaxSpreadPoints   = MaxSpreadPoints;
   }

   //--- Print broker symbol info for debugging
   PrintSymbolInfo();

   Print("Gold Multi-Strategy EA initialized successfully");
   Print("Current ATR: ", g_atrValue, " points (", g_atrValue/_Point, " pips)");
   Print("Risk per trade: ", RiskPerTrade, "%");

   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   if(handle_EMA_Fast != INVALID_HANDLE) IndicatorRelease(handle_EMA_Fast);
   if(handle_EMA_Slow != INVALID_HANDLE) IndicatorRelease(handle_EMA_Slow);
   if(handle_RSI != INVALID_HANDLE) IndicatorRelease(handle_RSI);
   if(handle_BB != INVALID_HANDLE) IndicatorRelease(handle_BB);
   if(handle_ADX != INVALID_HANDLE) IndicatorRelease(handle_ADX);
   if(handle_ATR != INVALID_HANDLE) IndicatorRelease(handle_ATR);
   if(handle_TrendMA != INVALID_HANDLE) IndicatorRelease(handle_TrendMA);
   Print("Gold Multi-Strategy EA deinitialized.");
}

//+------------------------------------------------------------------+
//| Expert tick function - Main processing loop                     |
//+------------------------------------------------------------------+
void OnTick() {
   //--- Daily reset check
   DailyResetCheck();

   //--- Update ATR every 12 bars (approx once per hour on M5)
   static int atrUpdateCounter = 0;
   atrUpdateCounter++;
   if(atrUpdateCounter >= 12) {
      g_atrValue = CalculateATRValue();
      atrUpdateCounter = 0;
   }

   //--- Manage open trades on every tick (trailing/breakeven/partial)
   ManageActiveTrades();

   //--- Check risk limits before opening anything new
   if(!CheckRiskLimits()) return;

   //--- Time filter
   if(UseTimeFilter && !IsWithinTradingHours()) return;

   //--- News filter (pause around high-impact events)
   if(eff_EnableNewsFilter && IsNewsTime()) {
      if(DebugMode) Print("News filter active - skipping new trades");
      return;
   }

   //--- Early exit if no new bar
   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(_Symbol, PERIOD_M5, 0);
   if(currentBarTime == lastBarTime) return;
   lastBarTime = currentBarTime;

   //--- Get latest indicator values
   double emaFast[], emaSlow[];
   double rsiValue[];
   double bbLower[], bbUpper[];
   double adxValue[], adxPlus[], adxMinus[];
   double atrValue[];

   ArraySetAsSeries(emaFast, true);
   ArraySetAsSeries(emaSlow, true);
   ArraySetAsSeries(rsiValue, true);
   ArraySetAsSeries(bbLower, true);
   ArraySetAsSeries(bbUpper, true);
   ArraySetAsSeries(adxValue, true);
   ArraySetAsSeries(adxPlus, true);
   ArraySetAsSeries(adxMinus, true);
   ArraySetAsSeries(atrValue, true);

   if(CopyBuffer(handle_EMA_Fast, 0, 0, 3, emaFast) < 3 ||
      CopyBuffer(handle_EMA_Slow, 0, 0, 3, emaSlow) < 3 ||
      CopyBuffer(handle_RSI, 0, 0, 3, rsiValue) < 3 ||
      CopyBuffer(handle_BB, 1, 0, 3, bbUpper) < 3 ||  // FIXED: buffer 1 = UPPER band
      CopyBuffer(handle_BB, 2, 0, 3, bbLower) < 3 ||  // FIXED: buffer 2 = LOWER band
      CopyBuffer(handle_ADX, 0, 0, 3, adxValue) < 3 ||
      CopyBuffer(handle_ADX, 1, 0, 3, adxPlus) < 3 ||
      CopyBuffer(handle_ADX, 2, 0, 3, adxMinus) < 3 ||
      CopyBuffer(handle_ATR, 0, 0, 1, atrValue) < 1) {
      return;
   }

   //--- Check for ADX trend strength (minimum threshold)
   if(adxValue[1] < eff_ADXThreshold) {
      if(DebugMode) Print("ADX too low: ", adxValue[1], " < ", eff_ADXThreshold);
      return;
   }

   //--- Get current price and spread
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double spread = ask - bid;
   double spreadPoints = spread / _Point;
   double minStopLevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;

   //--- Hard spread guard (FIXED: this actually blocks now)
   if(spreadPoints > eff_MaxSpreadPoints) {
      if(DebugMode) Print("Spread too high: ", spreadPoints, " > ", eff_MaxSpreadPoints);
      return;
   }

   //--- Evaluate all four strategies in parallel
   SignalData signal;
   signal.direction = 0;
   signal.quality = 0;
   double qualitySum = 0;
   int activeStrategies = 0;

   // Strategy 1: EMA 9/21 Crossover
   if(EnableStrategy1) {
      SignalData s1 = EvaluateEMACrossover(emaFast, emaSlow);
      qualitySum += s1.quality;
      if(s1.quality > 0) activeStrategies++;
      if(s1.direction != 0 && s1.quality > signal.quality) {
         signal.direction = s1.direction;
         signal.quality = s1.quality;
      }
      if(DebugMode && s1.quality > 0) Print("EMA Strategy: dir=", s1.direction, " qual=", s1.quality);
   }

   // Strategy 2: RSI Momentum
   if(EnableStrategy2) {
      SignalData s2 = EvaluateRSIStrategy(rsiValue, adxPlus, adxMinus);
      qualitySum += s2.quality;
      if(s2.quality > 0) activeStrategies++;
      if(s2.direction != 0 && s2.quality > signal.quality) {
         signal.direction = s2.direction;
         signal.quality = s2.quality;
      }
      if(DebugMode && s2.quality > 0) Print("RSI Strategy: dir=", s2.direction, " qual=", s2.quality);
   }

   // Strategy 3: Bollinger Bands
   if(EnableStrategy3) {
      SignalData s3 = EvaluateBollingerBands(bbLower, bbUpper, adxValue);
      qualitySum += s3.quality;
      if(s3.quality > 0) activeStrategies++;
      if(s3.direction != 0 && s3.quality > signal.quality) {
         signal.direction = s3.direction;
         signal.quality = s3.quality;
      }
      if(DebugMode && s3.quality > 0) Print("BB Strategy: dir=", s3.direction, " qual=", s3.quality);
   }

   // Strategy 4: Intraday Momentum
   if(EnableStrategy4) {
      SignalData s4 = EvaluateIntradayMomentum(adxPlus, adxMinus, atrValue, spread);
      qualitySum += s4.quality;
      if(s4.quality > 0) activeStrategies++;
      if(s4.direction != 0 && s4.quality > signal.quality) {
         signal.direction = s4.direction;
         signal.quality = s4.quality;
      }
      if(DebugMode && s4.quality > 0) Print("Momentum Strategy: dir=", s4.direction, " qual=", s4.quality);
   }

   //--- Calculate average quality across all strategies
   double avgQuality = (activeStrategies > 0) ? qualitySum / activeStrategies : 0;

   //--- Filter: only trade if signal quality is above threshold AND it's the best among active strategies
   if(signal.quality < avgQuality) {
      if(DebugMode && signal.quality > 0) Print("Signal rejected (below avg): ", signal.quality, " < ", avgQuality);
      return;
   }

   //--- Execute trade if quality threshold met
   if(signal.direction != 0 && signal.quality >= eff_MinSignalQuality) {

      //--- Respect long/short permissions (FIXED: these were ignored before)
      if(signal.direction == 1 && !TradeLong)  { if(DebugMode) Print("Longs disabled"); return; }
      if(signal.direction == -1 && !TradeShort) { if(DebugMode) Print("Shorts disabled"); return; }

      //--- Higher-timeframe trend filter (NEW)
      if(eff_EnableTrendFilter && !TrendAllows(signal.direction)) {
         if(DebugMode) Print("Trend filter blocked direction ", signal.direction);
         return;
      }

      //--- One trade per direction (NEW): don't stack same-direction trades
      if(OneTradePerDirection && CountPositionsByDirection(signal.direction) > 0) {
         if(DebugMode) Print("Already have a position in direction ", signal.direction);
         return;
      }

      double entryPrice = (signal.direction == 1) ? ask : bid;
      double slDistancePoints = g_atrValue / _Point * SL_ATR_Multiplier;  // ATR-based SL (FIXED: now uses SL_ATR_Multiplier)

      double sl = (signal.direction == 1) ? entryPrice - (slDistancePoints * _Point) : entryPrice + (slDistancePoints * _Point);
      // No fixed take-profit: the trade rides the trailing stop so winners can run for bigger profit.
      double tp = 0.0;

      //--- Validate stop levels
      if((signal.direction == 1 && (entryPrice - sl) < minStopLevel) ||
         (signal.direction == -1 && (sl - entryPrice) < minStopLevel)) {
         if(DebugMode) Print("Stop level too close to price, minStopLevel=", minStopLevel);
         return;
      }

      double lots = CalculateLotSize(slDistancePoints);
      ExecuteTrade(signal.direction, lots, sl, tp);

   } else if(DebugMode && signal.direction != 0) {
      Print("Signal quality too low: ", signal.quality, " < ", eff_MinSignalQuality);
   }
}

//+------------------------------------------------------------------+
//| EVALUATION FUNCTIONS                                            |
//+------------------------------------------------------------------+
SignalData EvaluateEMACrossover(double &emaFast[], double &emaSlow[]) {
   SignalData result;
   result.quality = 0;
   result.direction = 0;

   bool fastAboveSlow_prev = (emaFast[1] > emaSlow[1]);
   bool fastAboveSlow_curr = (emaFast[0] > emaSlow[0]);
   bool fastBelowSlow_prev = (emaFast[1] < emaSlow[1]);
   bool fastBelowSlow_curr = (emaFast[0] < emaSlow[0]);

   if(!fastAboveSlow_prev && fastAboveSlow_curr) {
      result.direction = 1;
      result.quality = 72.0;
      double slope = (emaFast[0] - emaFast[1]) / _Point;
      if(slope > 20) result.quality += 8.0;
   }
   else if(!fastBelowSlow_prev && fastBelowSlow_curr) {
      result.direction = -1;
      result.quality = 72.0;
      double slope = (emaFast[1] - emaFast[0]) / _Point;
      if(slope > 20) result.quality += 8.0;
   }
   return result;
}

SignalData EvaluateRSIStrategy(double &rsi[], double &adxPlus[], double &adxMinus[]) {
   SignalData result;
   result.quality = 0;
   result.direction = 0;

   if(rsi[1] < RSI_Oversold && rsi[0] > RSI_Oversold && rsi[0] < 50) {
      result.direction = 1;
      result.quality = 75.0;
      if(adxPlus[0] > adxMinus[0]) result.quality += 10.0;
   }
   else if(rsi[1] > RSI_Overbought && rsi[0] < RSI_Overbought && rsi[0] > 50) {
      result.direction = -1;
      result.quality = 75.0;
      if(adxMinus[0] > adxPlus[0]) result.quality += 10.0;
   }
   return result;
}

SignalData EvaluateBollingerBands(double &bbLower[], double &bbUpper[], double &adx[]) {
   SignalData result;
   result.quality = 0;
   result.direction = 0;
   double close = iClose(_Symbol, PERIOD_M5, 0);

   if(close <= bbLower[0]) {
      result.direction = 1;
      result.quality = 68.0;
      if(adx[0] < 25) result.quality += 10.0;
   }
   else if(close >= bbUpper[0]) {
      result.direction = -1;
      result.quality = 68.0;
      if(adx[0] < 25) result.quality += 10.0;
   }
   return result;
}

SignalData EvaluateIntradayMomentum(double &adxPlus[], double &adxMinus[], double &atr[], double spread) {
   SignalData result;
   result.quality = 0;
   result.direction = 0;

   double volatility = (atr[0] / _Point);
   if(volatility < 200 * MomentumVolatilityMultiplier) return result;

   if(adxPlus[0] > adxMinus[0] && adxPlus[0] > 25 && adxPlus[0] > adxPlus[1]) {
      result.direction = 1;
      result.quality = 65.0;
      if(adxPlus[0] > 30) result.quality += 10.0;
   }
   else if(adxMinus[0] > adxPlus[0] && adxMinus[0] > 25 && adxMinus[0] > adxMinus[1]) {
      result.direction = -1;
      result.quality = 65.0;
      if(adxMinus[0] > 30) result.quality += 10.0;
   }
   return result;
}

//+------------------------------------------------------------------+
//| FILTERS & HELPERS                                                |
//+------------------------------------------------------------------+

//--- Higher-timeframe trend filter: only allow trades WITH the HTF trend
bool TrendAllows(int direction) {
   double tm[];
   ArraySetAsSeries(tm, true);
   if(CopyBuffer(handle_TrendMA, 0, 0, 2, tm) < 2) return true;  // missing data -> don't block
   double closeHTF = iClose(_Symbol, TrendTimeframe, 0);
   if(direction == 1)  return (closeHTF > tm[0] && tm[0] >= tm[1]);   // uptrend
   if(direction == -1) return (closeHTF < tm[0] && tm[0] <= tm[1]);   // downtrend
   return false;
}

//--- Count EA's open positions in a given direction (1=BUY, -1=SELL)
int CountPositionsByDirection(int direction) {
   long wanted = (direction == 1) ? POSITION_TYPE_BUY : POSITION_TYPE_SELL;
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket)) {
         if(PositionGetInteger(POSITION_MAGIC) == MagicNumber &&
            PositionGetInteger(POSITION_TYPE) == wanted) count++;
      }
   }
   return count;
}

//--- News filter: pause around high-impact USD events (live/real-time only; tester returns none)
bool IsNewsTime() {
   datetime now  = TimeTradeServer();
   datetime from = now - NewsMinutesBefore * 60;
   datetime to   = now + NewsMinutesAfter * 60;

   MqlCalendarValue values[];
   int n = CalendarValueHistory(values, from, to, NULL, "USD");
   for(int i = 0; i < n; i++) {
      MqlCalendarEvent event;
      if(CalendarEventById(values[i].event_id, event)) {
         if(event.importance == CALENDAR_IMPORTANCE_HIGH) return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| RISK MANAGEMENT & TRADE EXECUTION FUNCTIONS                    |
//+------------------------------------------------------------------+

void DailyResetCheck() {
   datetime currentDay = iTime(_Symbol, PERIOD_D1, 0);
   if(currentDay != g_lastReset) {
      g_tradesToday = 0;
      g_dailyDrawdown = 0;
      g_tradingHalted = false;
      g_lastReset = currentDay;
      g_initialBalance = AccountInfoDouble(ACCOUNT_BALANCE);
      g_highestEquity = AccountInfoDouble(ACCOUNT_EQUITY);
      if(DebugMode) Print("Daily reset: new day, counters reset");
   }
}

bool CheckRiskLimits() {
   //--- Already halted for the day?
   if(g_tradingHalted) {
      if(DebugMode) Print("Trading halted for today (daily limit/target reached)");
      return false;
   }

   if(g_tradesToday >= MaxDailyTrades) {
      if(DebugMode) Print("Daily trade limit reached: ", g_tradesToday);
      return false;
   }
   if(CountOpenPositions() >= MaxConcurrentTrades) {
      if(DebugMode) Print("Max concurrent trades reached");
      return false;
   }

   double currentEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   if(currentEquity > g_highestEquity) g_highestEquity = currentEquity;

   //--- Trailing daily drawdown from equity peak -> hard halt for the day
   double drawdownPct = (g_highestEquity - currentEquity) / g_highestEquity * 100;
   if(drawdownPct > MaxDailyDrawdown) {
      g_tradingHalted = true;
      Print("HALT: Max daily drawdown reached: ", drawdownPct, "%");
      return false;
   }

   //--- Daily profit target -> lock in the day
   if(DailyProfitTargetPct > 0 && g_initialBalance > 0) {
      double dayPLpct = (currentEquity - g_initialBalance) / g_initialBalance * 100;
      if(dayPLpct >= DailyProfitTargetPct) {
         g_tradingHalted = true;
         Print("HALT: Daily profit target reached: ", dayPLpct, "%");
         return false;
      }
   }

   //--- Working portfolio-risk cap (FIXED: now sums REAL open positions by magic number)
   double openRisk = CalculateOpenRiskPercent();
   if(openRisk > MaxTotalRisk) {
      if(DebugMode) Print("Portfolio risk limit exceeded: ", openRisk, "% > ", MaxTotalRisk, "%");
      return false;
   }
   return true;
}

//--- Sum the % of balance at risk across all EA positions (distance to SL x value x lots)
double CalculateOpenRiskPercent() {
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   if(balance <= 0) return 0;

   double contractSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double valuePerPointPerLot = (tickSize > 0) ? contractSize * tickSize : 0;

   double totalRisk = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket) && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {
         double op  = PositionGetDouble(POSITION_PRICE_OPEN);
         double psl = PositionGetDouble(POSITION_SL);
         double vol = PositionGetDouble(POSITION_VOLUME);
         if(psl > 0) {
            double riskPoints = MathAbs(op - psl) / _Point;
            double riskMoney = riskPoints * valuePerPointPerLot * vol;
            totalRisk += riskMoney / balance * 100.0;
         }
      }
   }
   return totalRisk;
}

double CalculateATRValue() {
   double atr[1];
   if(CopyBuffer(handle_ATR, 0, 0, 1, atr) < 1) return 150 * _Point;
   return atr[0];
}

//+------------------------------------------------------------------+
//| CORRECTED LOT SIZE CALCULATION for Exness and any broker        |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePoints) {
   // 1. Risk amount in account currency
   double riskAmount = AccountInfoDouble(ACCOUNT_BALANCE) * (RiskPerTrade / 100.0);

   // 2. Manually calculate tick value using contract size and tick size
   double contractSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double manualTickValue = contractSize * tickSize;   // Correct value per point per lot

   // 3. Total loss if stop is hit for 1 lot
   double lossIfStopForOneLot = slDistancePoints * manualTickValue;
   if(lossIfStopForOneLot <= 0) return SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);

   // 4. Ideal lot size based on risk
   double lots = riskAmount / lossIfStopForOneLot;

   // 5. Normalize to broker's volume constraints
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);

   lots = MathFloor(lots / lotStep) * lotStep;
   lots = MathMax(lots, minLot);
   lots = MathMin(lots, maxLot);

   if(DebugMode) Print("Lot calc: riskAmount=", riskAmount,
                       " slPoints=", slDistancePoints,
                       " manualTickValue=", manualTickValue,
                       " lossIfStopForOneLot=", lossIfStopForOneLot,
                       " lots=", lots);

   return lots;
}

void ExecuteTrade(int direction, double lots, double sl, double tp) {
   MqlTradeRequest request = {};
   MqlTradeResult result = {};

   request.action = TRADE_ACTION_DEAL;
   request.symbol = _Symbol;
   request.volume = lots;
   request.deviation = 10;
   request.magic = MagicNumber;

   if(direction == 1) {
      request.type = ORDER_TYPE_BUY;
      request.price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      request.sl = sl;
      request.tp = tp;
      request.comment = "GoldEA_BUY";
   } else {
      request.type = ORDER_TYPE_SELL;
      request.price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      request.sl = sl;
      request.tp = tp;
      request.comment = "GoldEA_SELL";
   }

   if(OrderSend(request, result)) {
      if(result.retcode == TRADE_RETCODE_DONE) {
         g_tradesToday++;
         Print("TRADE EXECUTED: ", direction==1?"BUY":"SELL", " Lots: ", lots, " SL: ", sl, " TP: ", tp, " Ticket: ", result.order);
      } else {
         Print("Order send failed. Retcode: ", result.retcode, " - ", GetLastError());
      }
   } else {
      Print("OrderSend error: ", GetLastError());
   }
}

int CountOpenPositions() {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket)) {
         if(PositionGetInteger(POSITION_MAGIC) == MagicNumber) count++;
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| MANAGE ACTIVE TRADES                                             |
//| Trades have NO fixed take-profit. They follow the trailing stop  |
//| so a winning trade keeps running with the trend and only closes  |
//| when price pulls back to the trailing stop.                      |
//+------------------------------------------------------------------+
void ManageActiveTrades() {
   double breakevenBuffer = 5 * _Point;
   //--- Trailing distance: ATR-based (adapts to volatility) or fixed points
   double trailDist = UseATRTrailing ? (g_atrValue * TrailATRMultiplier) : (TrailingStep * _Point);

   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket)) {
         if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;

         bool isBuy = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY);
         double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
         double currentSL = PositionGetDouble(POSITION_SL);
         double currentTP = PositionGetDouble(POSITION_TP);
         double currentPrice = isBuy ? SymbolInfoDouble(_Symbol, SYMBOL_BID) :
                                       SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double profitPoints = isBuy ? (currentPrice - openPrice) / _Point :
                                       (openPrice - currentPrice) / _Point;

         //--- Move stop to breakeven once in profit (locks the trade, never closes it early)
         if(UseBreakeven && profitPoints >= BreakevenTrigger) {
            double beSL = openPrice + (isBuy ? breakevenBuffer : -breakevenBuffer);
            if(isBuy) {
               if(currentSL < beSL) { ModifyPosition(ticket, beSL, currentTP); currentSL = beSL; }
            } else {
               if(currentSL == 0 || currentSL > beSL) { ModifyPosition(ticket, beSL, currentTP); currentSL = beSL; }
            }
         }

         //--- Trailing stop: follows price, only ever moves in the trade's favour
         if(UseTrailingStop && profitPoints >= TrailingStart) {
            double newSL;
            if(isBuy) {
               newSL = currentPrice - trailDist;
               if(newSL > currentSL) ModifyPosition(ticket, newSL, currentTP);
            } else {
               newSL = currentPrice + trailDist;
               if(newSL < currentSL || currentSL == 0) ModifyPosition(ticket, newSL, currentTP);
            }
         }

         //--- Partial close OFF by default so the full size rides the trailing stop
         if(UsePartialClose && profitPoints >= (TrailingStart * 1.5) &&
            PositionGetDouble(POSITION_VOLUME) > SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN)) {
            double currentVolume = PositionGetDouble(POSITION_VOLUME);
            double closeVolume = currentVolume * (PartialClosePercent / 100.0);
            ClosePartialPosition(ticket, closeVolume);
         }
      }
   }
}

void ModifyPosition(ulong ticket, double newSL, double newTP) {
   MqlTradeRequest request = {};
   MqlTradeResult result = {};
   request.action = TRADE_ACTION_SLTP;
   request.position = ticket;
   request.sl = NormalizeDouble(newSL, _Digits);
   request.tp = NormalizeDouble(newTP, _Digits);
   if(!OrderSend(request, result)) {
      Print("SL/TP modification failed: ", result.retcode);
   }
}

void ClosePartialPosition(ulong ticket, double volume) {
   MqlTradeRequest request = {};
   MqlTradeResult result = {};
   request.action = TRADE_ACTION_DEAL;
   request.symbol = _Symbol;
   request.deviation = 10;
   request.position = ticket;
   if(PositionSelectByTicket(ticket)) {
      //--- Normalize partial volume to broker constraints
      double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
      double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
      volume = MathFloor(volume / lotStep) * lotStep;
      if(volume < minLot) return;
      request.volume = volume;

      request.type = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ?
                     ORDER_TYPE_SELL : ORDER_TYPE_BUY;
      request.price = (request.type == ORDER_TYPE_BUY) ?
                      SymbolInfoDouble(_Symbol, SYMBOL_ASK) :
                      SymbolInfoDouble(_Symbol, SYMBOL_BID);
      if(OrderSend(request, result) && result.retcode != TRADE_RETCODE_DONE) {
         Print("Partial close failed: ", result.retcode);
      }
   }
}

bool IsWithinTradingHours() {
   MqlDateTime currentTime;
   TimeCurrent(currentTime);
   int currentHour = currentTime.hour;
   return (currentHour >= StartHour && currentHour < EndHour);
}

//+------------------------------------------------------------------+
//| DIAGNOSTIC FUNCTION - Prints broker symbol specifications       |
//+------------------------------------------------------------------+
void PrintSymbolInfo() {
   Print("===== Symbol Info for ", _Symbol, " =====");
   Print("Contract Size: ", SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE));
   Print("Tick Size: ", SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE));
   Print("Tick Value (reported by broker): ", SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE));
   Print("Volume Step: ", SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP));
   Print("Min Volume: ", SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
   Print("Max Volume: ", SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));
   Print("Calculated Tick Value (Contract * Tick): ",
          SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE) *
          SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE));
   Print("========================================");
}
//+------------------------------------------------------------------+
