//+------------------------------------------------------------------+
//|                                          GoldMultiStrategyEA.mq5 |
//|                                    Generated by MetaEditor      |
//|                                                                  |
//| Multi-Strategy Gold Trading Bot - 4 strategies integrated       |
//+------------------------------------------------------------------+
#property copyright "Advanced Gold EA"
#property link      ""
#property version   "3.12"
#property description "Multi-Strategy Expert Advisor for Gold (XAUUSD)"
#property description "Combines EMA Crossover, RSI, Bollinger Bands & Intraday Momentum"
#property description "with proprietary Signal Quality Scoring & Adaptive Risk"
#property description "Exits ride the trailing stop (no fixed TP) to let winners run"

//+------------------------------------------------------------------+
//| INPUT PARAMETERS (Customizable by user in MT5)                 |
//+------------------------------------------------------------------+

//--- System Settings
input string   sys1 = "═════════ SYSTEM SETTINGS ═════════";        // --- SYSTEM SETTINGS ---
input ulong    MagicNumber = 202411;                                // EA Magic Number
input bool     TradeLong = true;                                    // Allow Long (BUY) Trades
input bool     TradeShort = true;                                   // Allow Short (SELL) Trades
input int      MaxConcurrentTrades = 200000;                             // Max Simultaneous Positions
input bool     UseTimeFilter = false;                                // Restrict Trading Hours
input int      StartHour = 8;                                       // Trading Start Hour (Broker Time)
input int      EndHour = 20;                                        // Trading End Hour (Broker Time)

//--- Risk Management
input string   risk1 = "══════════ RISK MANAGEMENT ══════════";     // --- RISK MANAGEMENT ---
input double   RiskPerTrade = 4.5;                                  // Risk % per Trade (0.5-2.0)
input double   MaxDailyDrawdown = 5.0;                              // Max Daily Drawdown %
input double   MaxTotalRisk = 10.0;                                 // Max Concurrent Portfolio Risk %
input int      MaxDailyTrades = 2000000000;                                  // Max Trades Per Day
input bool     UseBreakeven = true;                                 // Auto-Breakeven at X pips
input int      BreakevenTrigger = 15;                               // Breakeven trigger points (10-20)
input bool     UseTrailingStop = true;                              // Enable Trailing Stop
input int      TrailingStart = 40;                                  // Trailing start points (20-40)
input int      TrailingStep = 30;                                   // Trailing step points (10-20)
input bool     UsePartialClose = false;                             // Enable Partial Profit Taking (OFF = keep full size)
input double   PartialClosePercent = 50.0;                          // % to close at 1st TP
input double   RiskRewardRatio = 2.5;
input double   SL_ATR_Multiplier = 0.3;        // NEW: very tight stop (0.3 x ATR)                              // Risk:Reward Ratio (1.5-2.5)

//--- Strategy Selection & Quality
input string   strat1 = "══════════ STRATEGY SETUP ══════════";     // --- STRATEGY SETUP ---
input bool     EnableStrategy1 = true;                              // 1. EMA 9/21 Crossover
input bool     EnableStrategy2 = true;                              // 2. RSI Momentum Strategy
input bool     EnableStrategy3 = true;                              // 3. Bollinger Bands Strategy
input bool     EnableStrategy4 = true;                              // 4. Intraday Momentum Strategy
input double   MinSignalQuality = 65.0;                             // Min Signal Quality (0-100) - 60-70 recommended
input int      RSI_Period = 14;                                     // RSI Period
input double   RSI_Overbought = 70;                                 // RSI Overbought Level
input double   RSI_Oversold = 30;                                   // RSI Oversold Level
input int      BB_Period = 20;                                      // Bollinger Bands Period
input double   BB_Deviation = 2.0;                                  // Bollinger Bands Deviation
input double   MomentumVolatilityMultiplier = 1.5;                  // Momentum Min Volatility Multiplier

//--- Indicator Settings
input string   ind1 = "═══════════ INDICATOR SETTINGS ═════════";   // --- INDICATOR SETTINGS ---
input int      FastMAPeriod = 9;                                    // Fast EMA Period
input int      SlowMAPeriod = 21;                                   // Slow EMA Period
input int      ADXPeriod = 14;                                      // ADX Period for Trend Filter
input int      ADXThreshold = 20;                                   // ADX Minimum (20-25)
input int      ATRPeriod = 14;                                      // ATR Period for Dynamic SL/TP

//--- Debug mode (prints signal details)
input bool     DebugMode = true;                                    // Enable debug prints in Experts tab

//+------------------------------------------------------------------+
//| GLOBAL VARIABLES                                                |
//+------------------------------------------------------------------+
double g_atrValue = 0;
double g_dailyDrawdown = 0;
int g_tradesToday = 0;
datetime g_lastReset = 0;
double g_initialBalance = 0;
double g_highestEquity = 0;

//--- Strategy Signal Scoring
struct SignalData {
   double quality;     // Signal quality score (0-100)
   int direction;      // 1 = BUY, -1 = SELL, 0 = NEUTRAL
};

//--- Trade Structure
struct TradeInfo {
   ulong ticket;
   double openPrice;
   double sl;
   double tp;
   double lots;
   datetime openTime;
   int strategyID;
};

TradeInfo activeTrades[];
int g_totalActiveTrades = 0;

//--- Indicator Handles
int handle_EMA_Fast;
int handle_EMA_Slow;
int handle_RSI;
int handle_BB;
int handle_ADX;
int handle_ATR;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   //--- Validate inputs
   if(RiskPerTrade < 0.5 || RiskPerTrade > 5.0) {
      Print("WARNING: RiskPerTrade should be between 0.5 and 5.0");
      return(INIT_PARAMETERS_INCORRECT);
   }

   //--- Initialize indicator handles
   handle_EMA_Fast = iMA(_Symbol, PERIOD_M5, FastMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handle_EMA_Slow = iMA(_Symbol, PERIOD_M5, SlowMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handle_RSI = iRSI(_Symbol, PERIOD_M5, RSI_Period, PRICE_CLOSE);
   handle_BB = iBands(_Symbol, PERIOD_M5, BB_Period, BB_Deviation, 0, PRICE_CLOSE);
   handle_ADX = iADX(_Symbol, PERIOD_M5, ADXPeriod);
   handle_ATR = iATR(_Symbol, PERIOD_M5, ATRPeriod);

   if(handle_EMA_Fast == INVALID_HANDLE || handle_EMA_Slow == INVALID_HANDLE ||
      handle_RSI == INVALID_HANDLE || handle_BB == INVALID_HANDLE ||
      handle_ADX == INVALID_HANDLE || handle_ATR == INVALID_HANDLE) {
      Print("Error creating indicator handles. Check input parameters.");
      return(INIT_FAILED);
   }

   //--- Initialize global tracking
   g_initialBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   g_highestEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   g_tradesToday = 0;
   g_lastReset = iTime(_Symbol, PERIOD_D1, 0);
   g_atrValue = CalculateATRValue();

   //--- Print broker symbol info for debugging
   PrintSymbolInfo();

   Print("Gold Multi-Strategy EA initialized successfully");
   Print("Current ATR: ", g_atrValue, " points (", g_atrValue/_Point, " pips)");
   Print("Risk per trade: ", RiskPerTrade, "%");

   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   if(handle_EMA_Fast != INVALID_HANDLE) IndicatorRelease(handle_EMA_Fast);
   if(handle_EMA_Slow != INVALID_HANDLE) IndicatorRelease(handle_EMA_Slow);
   if(handle_RSI != INVALID_HANDLE) IndicatorRelease(handle_RSI);
   if(handle_BB != INVALID_HANDLE) IndicatorRelease(handle_BB);
   if(handle_ADX != INVALID_HANDLE) IndicatorRelease(handle_ADX);
   if(handle_ATR != INVALID_HANDLE) IndicatorRelease(handle_ATR);
   Print("Gold Multi-Strategy EA deinitialized.");
}

//+------------------------------------------------------------------+
//| Expert tick function - Main processing loop                     |
//+------------------------------------------------------------------+
void OnTick() {
   //--- Daily reset check
   DailyResetCheck();

   //--- Update ATR every 12 bars (approx once per hour on M5)
   static int atrUpdateCounter = 0;
   atrUpdateCounter++;
   if(atrUpdateCounter >= 12) {
      g_atrValue = CalculateATRValue();
      atrUpdateCounter = 0;
   }

   //--- Check risk limits before trading
   if(!CheckRiskLimits()) return;

   //--- Check time filter if enabled
   if(UseTimeFilter && !IsWithinTradingHours()) return;

   //--- Update active trades management (trailing/breakeven/partial)
   ManageActiveTrades();

   //--- Early exit if no new bar
   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(_Symbol, PERIOD_M5, 0);
   if(currentBarTime == lastBarTime) return;
   lastBarTime = currentBarTime;

   //--- Get latest indicator values
   double emaFast[], emaSlow[];
   double rsiValue[];
   double bbLower[], bbUpper[];
   double adxValue[], adxPlus[], adxMinus[];
   double atrValue[];

   ArraySetAsSeries(emaFast, true);
   ArraySetAsSeries(emaSlow, true);
   ArraySetAsSeries(rsiValue, true);
   ArraySetAsSeries(bbLower, true);
   ArraySetAsSeries(bbUpper, true);
   ArraySetAsSeries(adxValue, true);
   ArraySetAsSeries(adxPlus, true);
   ArraySetAsSeries(adxMinus, true);

   if(CopyBuffer(handle_EMA_Fast, 0, 0, 3, emaFast) < 3 ||
      CopyBuffer(handle_EMA_Slow, 0, 0, 3, emaSlow) < 3 ||
      CopyBuffer(handle_RSI, 0, 0, 3, rsiValue) < 3 ||
      CopyBuffer(handle_BB, 1, 0, 3, bbLower) < 3 ||
      CopyBuffer(handle_BB, 2, 0, 3, bbUpper) < 3 ||
      CopyBuffer(handle_ADX, 0, 0, 3, adxValue) < 3 ||
      CopyBuffer(handle_ADX, 1, 0, 3, adxPlus) < 3 ||
      CopyBuffer(handle_ADX, 2, 0, 3, adxMinus) < 3 ||
      CopyBuffer(handle_ATR, 0, 0, 1, atrValue) < 1) {
      return;
   }

   //--- Check for ADX trend strength (minimum threshold)
   if(adxValue[1] < ADXThreshold) {
      if(DebugMode) Print("ADX too low: ", adxValue[1], " < ", ADXThreshold);
      return;
   }

   //--- Get current price and spread
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double spread = ask - bid;
   double minStopLevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;

   //--- Evaluate all four strategies in parallel
   SignalData signal;
   signal.direction = 0;
   signal.quality = 0;
   double qualitySum = 0;
   int activeStrategies = 0;

   // Strategy 1: EMA 9/21 Crossover
   if(EnableStrategy1) {
      SignalData s1 = EvaluateEMACrossover(emaFast, emaSlow);
      qualitySum += s1.quality;
      if(s1.quality > 0) activeStrategies++;
      if(s1.direction != 0 && s1.quality > signal.quality) {
         signal.direction = s1.direction;
         signal.quality = s1.quality;
      }
      if(DebugMode && s1.quality > 0) Print("EMA Strategy: dir=", s1.direction, " qual=", s1.quality);
   }

   // Strategy 2: RSI Momentum
   if(EnableStrategy2) {
      SignalData s2 = EvaluateRSIStrategy(rsiValue, adxPlus, adxMinus);
      qualitySum += s2.quality;
      if(s2.quality > 0) activeStrategies++;
      if(s2.direction != 0 && s2.quality > signal.quality) {
         signal.direction = s2.direction;
         signal.quality = s2.quality;
      }
      if(DebugMode && s2.quality > 0) Print("RSI Strategy: dir=", s2.direction, " qual=", s2.quality);
   }

   // Strategy 3: Bollinger Bands
   if(EnableStrategy3) {
      SignalData s3 = EvaluateBollingerBands(bbLower, bbUpper, adxValue);
      qualitySum += s3.quality;
      if(s3.quality > 0) activeStrategies++;
      if(s3.direction != 0 && s3.quality > signal.quality) {
         signal.direction = s3.direction;
         signal.quality = s3.quality;
      }
      if(DebugMode && s3.quality > 0) Print("BB Strategy: dir=", s3.direction, " qual=", s3.quality);
   }

   // Strategy 4: Intraday Momentum
   if(EnableStrategy4) {
      SignalData s4 = EvaluateIntradayMomentum(adxPlus, adxMinus, atrValue, spread);
      qualitySum += s4.quality;
      if(s4.quality > 0) activeStrategies++;
      if(s4.direction != 0 && s4.quality > signal.quality) {
         signal.direction = s4.direction;
         signal.quality = s4.quality;
      }
      if(DebugMode && s4.quality > 0) Print("Momentum Strategy: dir=", s4.direction, " qual=", s4.quality);
   }

   //--- Calculate average quality across all strategies
   double avgQuality = (activeStrategies > 0) ? qualitySum / activeStrategies : 0;

   //--- Filter: only trade if signal quality is above threshold AND it's the best among active strategies
   if(signal.quality < avgQuality) {
      if(DebugMode && signal.quality > 0) Print("Signal rejected (below avg): ", signal.quality, " < ", avgQuality);
      return;
   }

   //--- Execute trade if quality threshold met
   if(signal.direction != 0 && signal.quality >= MinSignalQuality) {
      double entryPrice = (signal.direction == 1) ? ask : bid;
      double slDistancePoints = g_atrValue / _Point * 1.2;  // ATR-based SL in points (used for risk/lot sizing)

      double sl = (signal.direction == 1) ? entryPrice - (slDistancePoints * _Point) : entryPrice + (slDistancePoints * _Point);
      // No fixed take-profit: the trade rides the trailing stop so winners can run for bigger profit.
      // The position is only closed when the trailing stop (which follows the price) is hit.
      double tp = 0.0;

      //--- Validate stop levels
      if((signal.direction == 1 && (entryPrice - sl) < minStopLevel) ||
         (signal.direction == -1 && (sl - entryPrice) < minStopLevel)) {
         if(DebugMode) Print("Stop level too close to price, minStopLevel=", minStopLevel);
         return;
      }

      double lots = CalculateLotSize(slDistancePoints);  // Pass points now

      //--- Check spread before trading
      if(spread < SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * _Point * 1.5 || !UseTimeFilter) {
         ExecuteTrade(signal.direction, lots, sl, tp);
      } else if(DebugMode) {
         Print("Spread too high: ", spread/_Point, " points");
      }
   } else if(DebugMode && signal.direction != 0) {
      Print("Signal quality too low: ", signal.quality, " < ", MinSignalQuality);
   }
}

//+------------------------------------------------------------------+
//| EVALUATION FUNCTIONS                                            |
//+------------------------------------------------------------------+
SignalData EvaluateEMACrossover(double &emaFast[], double &emaSlow[]) {
   SignalData result;
   result.quality = 0;
   result.direction = 0;

   bool fastAboveSlow_prev = (emaFast[1] > emaSlow[1]);
   bool fastAboveSlow_curr = (emaFast[0] > emaSlow[0]);
   bool fastBelowSlow_prev = (emaFast[1] < emaSlow[1]);
   bool fastBelowSlow_curr = (emaFast[0] < emaSlow[0]);

   if(!fastAboveSlow_prev && fastAboveSlow_curr) {
      result.direction = 1;
      result.quality = 72.0;
      double slope = (emaFast[0] - emaFast[1]) / _Point;
      if(slope > 20) result.quality += 8.0;
   }
   else if(!fastBelowSlow_prev && fastBelowSlow_curr) {
      result.direction = -1;
      result.quality = 72.0;
      double slope = (emaFast[1] - emaFast[0]) / _Point;
      if(slope > 20) result.quality += 8.0;
   }
   return result;
}

SignalData EvaluateRSIStrategy(double &rsi[], double &adxPlus[], double &adxMinus[]) {
   SignalData result;
   result.quality = 0;
   result.direction = 0;

   if(rsi[1] < RSI_Oversold && rsi[0] > RSI_Oversold && rsi[0] < 50) {
      result.direction = 1;
      result.quality = 75.0;
      if(adxPlus[0] > adxMinus[0]) result.quality += 10.0;
   }
   else if(rsi[1] > RSI_Overbought && rsi[0] < RSI_Overbought && rsi[0] > 50) {
      result.direction = -1;
      result.quality = 75.0;
      if(adxMinus[0] > adxPlus[0]) result.quality += 10.0;
   }
   return result;
}

SignalData EvaluateBollingerBands(double &bbLower[], double &bbUpper[], double &adx[]) {
   SignalData result;
   result.quality = 0;
   result.direction = 0;
   double close = iClose(_Symbol, PERIOD_M5, 0);

   if(close <= bbLower[0]) {
      result.direction = 1;
      result.quality = 68.0;
      if(adx[0] < 25) result.quality += 10.0;
   }
   else if(close >= bbUpper[0]) {
      result.direction = -1;
      result.quality = 68.0;
      if(adx[0] < 25) result.quality += 10.0;
   }
   return result;
}

SignalData EvaluateIntradayMomentum(double &adxPlus[], double &adxMinus[], double &atr[], double spread) {
   SignalData result;
   result.quality = 0;
   result.direction = 0;

   double volatility = (atr[0] / _Point);
   if(volatility < 200 * MomentumVolatilityMultiplier) return result;

   if(adxPlus[0] > adxMinus[0] && adxPlus[0] > 25 && adxPlus[0] > adxPlus[1]) {
      result.direction = 1;
      result.quality = 65.0;
      if(adxPlus[0] > 30) result.quality += 10.0;
   }
   else if(adxMinus[0] > adxPlus[0] && adxMinus[0] > 25 && adxMinus[0] > adxMinus[1]) {
      result.direction = -1;
      result.quality = 65.0;
      if(adxMinus[0] > 30) result.quality += 10.0;
   }
   return result;
}

//+------------------------------------------------------------------+
//| RISK MANAGEMENT & TRADE EXECUTION FUNCTIONS                    |
//+------------------------------------------------------------------+

void DailyResetCheck() {
   datetime currentDay = iTime(_Symbol, PERIOD_D1, 0);
   if(currentDay != g_lastReset) {
      g_tradesToday = 0;
      g_dailyDrawdown = 0;
      g_lastReset = currentDay;
      g_initialBalance = AccountInfoDouble(ACCOUNT_BALANCE);
      g_highestEquity = AccountInfoDouble(ACCOUNT_EQUITY);
      if(DebugMode) Print("Daily reset: new day, trades today reset to 0");
   }
}

bool CheckRiskLimits() {
   if(g_tradesToday >= MaxDailyTrades) {
      if(DebugMode) Print("Daily trade limit reached: ", g_tradesToday);
      return false;
   }
   if(CountOpenPositions() >= MaxConcurrentTrades) {
      if(DebugMode) Print("Max concurrent trades reached");
      return false;
   }

   double currentEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   double drawdownPct = (g_highestEquity - currentEquity) / g_highestEquity * 100;
   if(drawdownPct > MaxDailyDrawdown) {
      if(DebugMode) Print("Max daily drawdown reached: ", drawdownPct, "%");
      return false;
   }
   if(currentEquity > g_highestEquity) g_highestEquity = currentEquity;

   double totalRisk = 0;
   for(int i = 0; i < g_totalActiveTrades; i++) {
      if(activeTrades[i].openPrice > 0) {
         double risk = MathAbs(activeTrades[i].openPrice - activeTrades[i].sl) * activeTrades[i].lots;
         totalRisk += risk / AccountInfoDouble(ACCOUNT_BALANCE) * 100;
      }
   }
   if(totalRisk > MaxTotalRisk) {
      if(DebugMode) Print("Portfolio risk limit exceeded: ", totalRisk, "%");
      return false;
   }
   return true;
}

double CalculateATRValue() {
   double atr[1];
   if(CopyBuffer(handle_ATR, 0, 0, 1, atr) < 1) return 150 * _Point;
   return atr[0];
}

//+------------------------------------------------------------------+
//| CORRECTED LOT SIZE CALCULATION for Exness and any broker        |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePoints) {
   // 1. Risk amount in account currency
   double riskAmount = AccountInfoDouble(ACCOUNT_BALANCE) * (RiskPerTrade / 100.0);

   // 2. Manually calculate tick value using contract size and tick size
   double contractSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double manualTickValue = contractSize * tickSize;   // Correct value per point per lot

   // 3. Total loss if stop is hit for 1 lot
   double lossIfStopForOneLot = slDistancePoints * manualTickValue;

   // 4. Ideal lot size based on risk
   double lots = riskAmount / lossIfStopForOneLot;

   // 5. Normalize to broker's volume constraints
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);

   lots = MathFloor(lots / lotStep) * lotStep;
   lots = MathMax(lots, minLot);
   lots = MathMin(lots, maxLot);

   if(DebugMode) Print("Lot calc: riskAmount=", riskAmount,
                       " slPoints=", slDistancePoints,
                       " manualTickValue=", manualTickValue,
                       " lossIfStopForOneLot=", lossIfStopForOneLot,
                       " lots=", lots);

   return lots;
}

void ExecuteTrade(int direction, double lots, double sl, double tp) {
   MqlTradeRequest request = {};
   MqlTradeResult result = {};

   request.action = TRADE_ACTION_DEAL;
   request.symbol = _Symbol;
   request.volume = lots;
   request.deviation = 10;
   request.magic = MagicNumber;

   if(direction == 1) {
      request.type = ORDER_TYPE_BUY;
      request.price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      request.sl = sl;
      request.tp = tp;
      request.comment = "GoldEA_BUY";
   } else {
      request.type = ORDER_TYPE_SELL;
      request.price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      request.sl = sl;
      request.tp = tp;
      request.comment = "GoldEA_SELL";
   }

   if(OrderSend(request, result)) {
      if(result.retcode == TRADE_RETCODE_DONE) {
         g_tradesToday++;
         Print("TRADE EXECUTED: ", direction==1?"BUY":"SELL", " Lots: ", lots, " SL: ", sl, " TP: ", tp, " Ticket: ", result.order);
      } else {
         Print("Order send failed. Retcode: ", result.retcode, " - ", GetLastError());
      }
   } else {
      Print("OrderSend error: ", GetLastError());
   }
}

int CountOpenPositions() {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket)) {
         if(PositionGetInteger(POSITION_MAGIC) == MagicNumber) count++;
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| MANAGE ACTIVE TRADES                                             |
//| Trades have NO fixed take-profit. They follow the trailing stop  |
//| so a winning trade keeps running with the trend and only closes  |
//| when price pulls back to the trailing stop.                      |
//+------------------------------------------------------------------+
void ManageActiveTrades() {
   double breakevenBuffer = 5 * _Point;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket)) {
         if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;

         double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
         double currentSL = PositionGetDouble(POSITION_SL);
         double currentTP = PositionGetDouble(POSITION_TP);
         double currentPrice = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ?
                               SymbolInfoDouble(_Symbol, SYMBOL_BID) :
                               SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double profitPoints = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ?
                               (currentPrice - openPrice) / _Point :
                               (openPrice - currentPrice) / _Point;

         //--- Move stop to breakeven once the trade is in profit (locks the trade, never closes it early)
         if(UseBreakeven && profitPoints >= BreakevenTrigger) {
            double newSL = openPrice + (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY ?
                          breakevenBuffer : -breakevenBuffer);
            if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
               if(currentSL < newSL) { ModifyPosition(ticket, newSL, currentTP); currentSL = newSL; }
            } else {
               if(currentSL == 0 || currentSL > newSL) { ModifyPosition(ticket, newSL, currentTP); currentSL = newSL; }
            }
            if(DebugMode) Print("Breakeven set for ticket ", ticket);
         }

         //--- Trailing stop: follows the price so profit keeps locking in as the trend runs.
         //--- The SL only ever moves in the trade's favour, so the position is never closed early.
         if(UseTrailingStop && profitPoints >= TrailingStart) {
            double newSL = 0;
            if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
               newSL = currentPrice - (TrailingStep * _Point);
               if(newSL > currentSL) ModifyPosition(ticket, newSL, currentTP);
            } else {
               newSL = currentPrice + (TrailingStep * _Point);
               if(newSL < currentSL || currentSL == 0) ModifyPosition(ticket, newSL, currentTP);
            }
         }

         //--- Partial close is OFF by default (UsePartialClose=false) so the full size stays open
         //--- and rides the trailing stop for the largest possible profit.
         if(UsePartialClose && profitPoints >= (TrailingStart * 1.5) &&
            PositionGetDouble(POSITION_VOLUME) > SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN)) {
            double currentVolume = PositionGetDouble(POSITION_VOLUME);
            double closeVolume = currentVolume * (PartialClosePercent / 100.0);
            ClosePartialPosition(ticket, closeVolume);
         }
      }
   }
}

void ModifyPosition(ulong ticket, double newSL, double newTP) {
   MqlTradeRequest request = {};
   MqlTradeResult result = {};
   request.action = TRADE_ACTION_SLTP;
   request.position = ticket;
   request.sl = newSL;
   request.tp = newTP;
   if(!OrderSend(request, result)) {
      Print("SL/TP modification failed: ", result.retcode);
   }
}

void ClosePartialPosition(ulong ticket, double volume) {
   MqlTradeRequest request = {};
   MqlTradeResult result = {};
   request.action = TRADE_ACTION_DEAL;
   request.symbol = _Symbol;
   request.volume = volume;
   request.deviation = 10;
   request.position = ticket;
   if(PositionSelectByTicket(ticket)) {
      request.type = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ?
                     ORDER_TYPE_SELL : ORDER_TYPE_BUY;
      request.price = (request.type == ORDER_TYPE_BUY) ?
                      SymbolInfoDouble(_Symbol, SYMBOL_ASK) :
                      SymbolInfoDouble(_Symbol, SYMBOL_BID);
      if(OrderSend(request, result) && result.retcode != TRADE_RETCODE_DONE) {
         Print("Partial close failed: ", result.retcode);
      }
   }
}

bool IsWithinTradingHours() {
   MqlDateTime currentTime;
   TimeCurrent(currentTime);
   int currentHour = currentTime.hour;
   return (currentHour >= StartHour && currentHour < EndHour);
}

//+------------------------------------------------------------------+
//| DIAGNOSTIC FUNCTION - Prints broker symbol specifications       |
//+------------------------------------------------------------------+
void PrintSymbolInfo() {
   Print("===== Symbol Info for ", _Symbol, " =====");
   Print("Contract Size: ", SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE));
   Print("Tick Size: ", SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE));
   Print("Tick Value (reported by broker): ", SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE));
   Print("Volume Step: ", SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP));
   Print("Min Volume: ", SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
   Print("Max Volume: ", SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));
   Print("Calculated Tick Value (Contract * Tick): ",
          SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE) *
          SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE));
   Print("========================================");
}
//+------------------------------------------------------------------+
